################################################################################
#    (C) Copyright 2016 CEA LIST. All Rights Reserved.
#    Contributor(s): Olivier BICHLER (olivier.bichler@cea.fr)
#
#    This software is governed by the CeCILL-C license under French law and
#    abiding by the rules of distribution of free software.  You can  use,
#    modify and/ or redistribute the software under the terms of the CeCILL-C
#    license as circulated by CEA, CNRS and INRIA at the following URL
#    "http://www.cecill.info".
#
#    As a counterpart to the access to the source code and  rights to copy,
#    modify and redistribute granted by the license, users are provided only
#    with a limited warranty  and the software's author,  the holder of the
#    economic rights,  and the successive licensors  have only  limited
#    liability.
#
#    The fact that you are presently reading this means that you have had
#    knowledge of the CeCILL-C license and that you accept its terms.
################################################################################

dist: trusty
sudo: required

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  #- clang
  - gcc

env:
  global:
    - NUM_THREADS=4
    - LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/lib:/lib64:/lib:/usr/lib64:/usr/lib:/usr/local/lib"

  matrix:
    - BUILD_NAME="make"
    - BUILD_NAME="make-cuda" USE_CUDA=1
    - BUILD_NAME="cmake" USE_CMAKE=1
    - BUILD_NAME="cmake-cuda" USE_CMAKE=1 USE_CUDA=1

cache:
  apt: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev libcv-dev libhighgui-dev
  - sudo apt-get install -y gnuplot
  - sudo -E ./.travis/install.sh

# Build steps
script:
  - ./.travis/build.sh
