################################################################################
#    (C) Copyright 2016 CEA LIST. All Rights Reserved.
#    Contributor(s): Olivier BICHLER (olivier.bichler@cea.fr)
#
#    This software is governed by the CeCILL-C license under French law and
#    abiding by the rules of distribution of free software.  You can  use,
#    modify and/ or redistribute the software under the terms of the CeCILL-C
#    license as circulated by CEA, CNRS and INRIA at the following URL
#    "http://www.cecill.info".
#
#    As a counterpart to the access to the source code and  rights to copy,
#    modify and redistribute granted by the license, users are provided only
#    with a limited warranty  and the software's author,  the holder of the
#    economic rights,  and the successive licensors  have only  limited
#    liability.
#
#    The fact that you are presently reading this means that you have had
#    knowledge of the CeCILL-C license and that you accept its terms.
################################################################################

os: Visual Studio 2015
configuration: Release
platform: x64

environment:
  DIRENT_INCLUDE_DIR: C:\projects\dirent\include
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    BUILD_TARGET: Visual Studio 12 2013 Win64
    OPENCV_BIN: C:\tools\opencv\build\x64\vc12\bin
    OpenCV_DIR: C:\tools\opencv\build
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    BUILD_TARGET: Visual Studio 12 2013 Win64
    OPENCV_BIN: C:\tools\opencv\build\x64\vc12\bin
    OpenCV_DIR: C:\tools\opencv\build
    USE_CUDA: 1
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    BUILD_TARGET: Visual Studio 14 2015 Win64
    OPENCV_BIN: C:\tools_vc14\opencv\build\x64\vc14\bin
    OpenCV_DIR: C:\tools_vc14\opencv\build
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    BUILD_TARGET: Visual Studio 14 2015 Win64
    OPENCV_BIN: C:\tools_vc14\opencv\build\x64\vc14\bin
    OpenCV_DIR: C:\tools_vc14\opencv\build
    USE_CUDA: 1

install:
  - cmd: .appveyor\install.cmd

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files\gnuplot -> appveyor.yml
  - C:\tools\opencv -> appveyor.yml
  - C:\tools_vc14\opencv -> appveyor.yml

before_build:
  - cmd: SET PATH=C:\Program Files\gnuplot\bin;%PATH%
  - mkdir build
  - cd build
  - cmake .. -G"%BUILD_TARGET%"
  - cmd: SET PATH=%OPENCV_BIN%;%PATH%

matrix:
  fast_finish: true

build:
  parallel: true
  verbosity: minimal
